delegation:
  requests: signing/delegation_requests
  delegations: signing/delegations
rules:
  "*":
    minimum_signatures: 1  # number of signers
    signers:
      signing/people:
        minimum_proportion: 0.51  # proportion of signers